import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-roboto antialiased">
        <nav className="fixed top-0 w-full z-40 bg-[#092071]/50 backdrop-blur-sm">
          <section className="max-w-2xl mx-auto px-3 py-3 flex justify-between items-center text-lg text-white font-semibold">
            Mini Market Deportivo
          </section>
        </nav>
        {children}
      </body>
    </html>
  );
}
